/**
 * LEGACY — NOT IN LIVE PATH
 *
 * This file is NOT mounted in the live scene. The live mandala path is:
 *   AsteroidScene → supr/SuprStage → supr/LotusField (baseline) + supr/FoldField (candidate)
 *
 * This file's TYPES (MandalaParams, MANDALA_DEFAULTS, MANDALA_PRESETS) are still
 * imported by AsteroidScene for a legacy control block (wrapped in {false && ...}).
 * That legacy block does not render.
 *
 * Do not edit this file expecting visual changes. Edit supr/LotusField.tsx or supr/FoldField.tsx instead.
 */
import { Canvas, useFrame, useThree } from '@react-three/fiber'
import { Bloom, EffectComposer, Noise, Vignette } from '@react-three/postprocessing'
import { useMemo, useRef } from 'react'
import * as THREE from 'three'

export type MandalaParams = {
  folds: number
  iters: number
  speed: number
  zoom: number
  scale: number
  lineWidth: number
  glow: number
  warp: number
  twist: number
  layerSpread: number
  contrast: number
  pulse: number
  fill: number
  depth: number
  particles: number
  bloom: number
  colorMode: 'mono' | 'spectrum'
  colorFg: string
  colorBg: string
  animate: boolean
  strobeRate: number
  strobeDuty: number
  strobeColor: string
}

export const MANDALA_DEFAULTS: MandalaParams = {
  folds: 7,
  iters: 9,
  speed: 0.12,
  zoom: 2.2,
  scale: 1.82,
  lineWidth: 1.05,
  glow: 1.15,
  warp: 0.32,
  twist: 0.4,
  layerSpread: 1.62,
  contrast: 1.1,
  pulse: 0.18,
  fill: 0.48,
  depth: 0.72,
  particles: 0.55,
  bloom: 0.85,
  colorMode: 'spectrum',
  colorFg: '#f4f1ff',
  colorBg: '#040109',
  animate: true,
  strobeRate: 0,
  strobeDuty: 0.15,
  strobeColor: '#ffffff',
}

export const MANDALA_PRESETS: { name: string; values: Partial<MandalaParams> }[] = [
  {
    name: 'Q900',
    values: {
      folds: 7,
      iters: 9,
      speed: 0.12,
      zoom: 2.2,
      scale: 1.82,
      lineWidth: 1.05,
      glow: 1.15,
      warp: 0.32,
      twist: 0.4,
      layerSpread: 1.62,
      contrast: 1.1,
      pulse: 0.18,
      fill: 0.48,
      depth: 0.72,
      particles: 0.55,
      bloom: 0.85,
      colorMode: 'spectrum',
      colorFg: '#f4f1ff',
      colorBg: '#040109',
    },
  },
  {
    name: 'CATHEDRAL',
    values: {
      folds: 12,
      iters: 10,
      speed: 0.05,
      zoom: 2.9,
      scale: 1.56,
      lineWidth: 0.72,
      glow: 1.4,
      warp: 0.08,
      twist: 0.22,
      layerSpread: 1.78,
      contrast: 1.22,
      pulse: 0.08,
      fill: 0.72,
      depth: 0.94,
      particles: 0.22,
      bloom: 1.1,
      colorMode: 'mono',
      colorFg: '#ffd88f',
      colorBg: '#07020f',
    },
  },
  {
    name: 'BLOODLOTUS',
    values: {
      folds: 8,
      iters: 9,
      speed: 0.16,
      zoom: 2.45,
      scale: 1.74,
      lineWidth: 1.24,
      glow: 1.55,
      warp: 0.66,
      twist: 0.62,
      layerSpread: 1.5,
      contrast: 1.2,
      pulse: 0.24,
      fill: 0.56,
      depth: 0.86,
      particles: 0.42,
      bloom: 1.25,
      colorMode: 'spectrum',
      colorFg: '#ff6c8c',
      colorBg: '#130007',
    },
  },
  {
    name: 'LIQUID',
    values: {
      folds: 5,
      iters: 8,
      speed: 0.09,
      zoom: 1.85,
      scale: 1.96,
      lineWidth: 1.45,
      glow: 1.7,
      warp: 1.15,
      twist: 0.36,
      layerSpread: 1.36,
      contrast: 1.0,
      pulse: 0.34,
      fill: 0.82,
      depth: 0.8,
      particles: 0.38,
      bloom: 1.35,
      colorMode: 'mono',
      colorFg: '#d9f8ff',
      colorBg: '#02070b',
    },
  },
  {
    name: 'SUPERNOVA',
    values: {
      folds: 14,
      iters: 11,
      speed: 0.2,
      zoom: 3.25,
      scale: 1.66,
      lineWidth: 0.8,
      glow: 2.0,
      warp: 0.38,
      twist: 0.94,
      layerSpread: 1.85,
      contrast: 1.34,
      pulse: 0.16,
      fill: 0.42,
      depth: 1.0,
      particles: 0.76,
      bloom: 1.75,
      colorMode: 'spectrum',
      colorFg: '#fff2a8',
      colorBg: '#040112',
    },
  },
  {
    name: 'OBSIDIAN',
    values: {
      folds: 7,
      iters: 12,
      speed: 0.055,
      zoom: 2.0,
      scale: 1.98,
      lineWidth: 0.68,
      glow: 0.55,
      warp: 0.08,
      twist: 0.1,
      layerSpread: 1.44,
      contrast: 1.42,
      pulse: 0.04,
      fill: 0.22,
      depth: 0.52,
      particles: 0.08,
      bloom: 0.45,
      colorMode: 'mono',
      colorFg: '#f5f2ff',
      colorBg: '#020202',
    },
  },
  {
    name: 'FRACTURE',
    values: {
      folds: 16,
      iters: 10,
      speed: 0.15,
      zoom: 2.8,
      scale: 1.58,
      lineWidth: 0.66,
      glow: 1.18,
      warp: 0.04,
      twist: 1.0,
      layerSpread: 1.73,
      contrast: 1.46,
      pulse: 0.06,
      fill: 0.28,
      depth: 0.94,
      particles: 0.2,
      bloom: 0.95,
      colorMode: 'mono',
      colorFg: '#ffffff',
      colorBg: '#070913',
    },
  },
  {
    name: 'ORACLE',
    values: {
      folds: 9,
      iters: 9,
      speed: 0.11,
      zoom: 2.35,
      scale: 1.73,
      lineWidth: 0.92,
      glow: 1.18,
      warp: 0.24,
      twist: 0.5,
      layerSpread: 1.6,
      contrast: 1.12,
      pulse: 0.14,
      fill: 0.64,
      depth: 0.86,
      particles: 0.28,
      bloom: 1.0,
      colorMode: 'spectrum',
      colorFg: '#ffe27a',
      colorBg: '#090312',
    },
  },
  {
    name: 'MORPH',
    values: {
      folds: 6,
      iters: 8,
      speed: 0.13,
      zoom: 1.95,
      scale: 1.9,
      lineWidth: 1.38,
      glow: 1.52,
      warp: 1.22,
      twist: 0.72,
      layerSpread: 1.34,
      contrast: 1.02,
      pulse: 0.38,
      fill: 0.88,
      depth: 0.88,
      particles: 0.52,
      bloom: 1.28,
      colorMode: 'spectrum',
      colorFg: '#89f6ef',
      colorBg: '#020713',
    },
  },
]

const VERT = `
varying vec2 vUv;

void main() {
  vUv = uv;
  vec4 mvPosition = modelViewMatrix * vec4(position, 1.0);
  gl_Position = projectionMatrix * mvPosition;
}
`

const FRAG = `
precision highp float;
varying vec2 vUv;

uniform float uTime;
uniform float uFolds;
uniform float uIters;
uniform float uSpeed;
uniform float uZoom;
uniform float uScale;
uniform float uLineWidth;
uniform float uGlow;
uniform float uWarp;
uniform float uTwist;
uniform float uLayerSpread;
uniform float uContrast;
uniform float uPulse;
uniform float uFill;
uniform float uOpacity;
uniform float uSeed;
uniform float uColorMode;
uniform vec3 uColorFg;
uniform vec3 uColorBg;
uniform vec2 uResolution;
uniform float uStrobeRate;
uniform float uStrobeDuty;
uniform vec3 uStrobeColor;

#define PI 3.14159265359
#define TAU 6.28318530718
#define PHI 1.61803398875

mat2 rot(float a) {
  float c = cos(a);
  float s = sin(a);
  return mat2(c, -s, s, c);
}

vec3 screenBlend(vec3 base, vec3 layer) {
  return 1.0 - (1.0 - clamp(base, 0.0, 1.0)) * (1.0 - clamp(layer, 0.0, 1.0));
}

vec2 domainWarp(vec2 p, float time, float warp) {
  if (warp <= 0.0001) return p;
  vec2 flow = vec2(
    sin(p.y * 3.1 + time * 0.83) + cos(p.x * 2.2 - time * 0.57),
    cos(p.x * 2.7 - time * 0.71) - sin(p.y * 2.4 + time * 0.49)
  );
  return p + flow * warp * 0.14;
}

vec3 kaleidoscopeLayer(
  vec2 uv,
  float time,
  float folds,
  float iters,
  float baseScale,
  float lineWidth,
  float glowStrength,
  float warp,
  float twist,
  float fillStrength
) {
  float angle = atan(uv.y, uv.x);
  float sector = TAU / folds;
  angle = mod(angle, sector);
  if (angle > sector * 0.5) angle = sector - angle;

  float r = length(uv);
  vec2 p = r * vec2(cos(angle), sin(angle));
  p = domainWarp(p, time, warp * 0.5);

  float foldAngle = PI / folds + (0.08 + 0.08 * twist) * sin(time * (0.28 + 0.1 * twist));
  float sc = baseScale + 0.22 * sin(time * 0.17) + warp * 0.05;
  vec2 offset = vec2(
    1.0 + warp * 0.08 * sin(time * 0.31),
    0.8 + 0.2 * sin(time * 0.23)
  );

  float lineMask = 0.0;
  float glowMask = 0.0;
  float fillMask = 0.0;
  float weight = 1.0;

  for (int i = 0; i < 14; i++) {
    if (float(i) >= iters) break;

    p = abs(p);
    p = domainWarp(p, time + float(i) * 0.17, warp * (0.35 + float(i) * 0.04));

    float a = foldAngle + float(i) * mix(0.04, 0.11, twist);
    p = rot(a) * p;
    p = p * sc - offset;

    float d1 = abs(p.x);
    float d2 = abs(p.y);
    float d3 = abs(p.x + p.y) * 0.70710678;
    float d4 = abs(p.x - p.y) * 0.70710678;
    float d5 = abs(length(p) - (0.42 + 0.16 * warp * sin(time * 0.39 + float(i) * 0.7)));
    float d6 = abs(
      length(
        p + vec2(
          sin(time * 0.55 + float(i) * 0.9),
          cos(time * 0.47 - float(i) * 0.73)
        ) * warp * 0.26
      ) - (0.28 + 0.12 * sin(time * 0.61 + float(i) * 0.41))
    );

    float d = min(min(d1, d2), min(min(d3, d4), min(d5, d6)));
    float fw = fwidth(d);
    float line = weight * smoothstep(fw * (1.0 + lineWidth), 0.0, d);
    float glow = exp(-abs(d) * (14.0 + weight * 8.0) / max(lineWidth, 0.15)) * weight * (0.14 + glowStrength * 0.08);
    float fill = smoothstep((0.18 + warp * 0.08) * (1.0 + lineWidth * 0.15), 0.0, d) * fillStrength * weight;

    lineMask = max(lineMask, line);
    glowMask += glow;
    fillMask = max(fillMask, fill);
    weight *= 0.67;
  }

  return vec3(clamp(lineMask, 0.0, 1.0), clamp(glowMask, 0.0, 1.0), clamp(fillMask, 0.0, 1.0));
}

void main() {
  vec2 uv = (vUv - 0.5) * 2.0;
  uv.x *= uResolution.x / uResolution.y;

  float time = uTime * uSpeed + uSeed * 0.7;
  float zoomPulse = 1.0 + sin(time * 0.5 + uSeed) * uPulse * 0.45;
  uv *= (uZoom + (0.18 + uPulse * 0.28) * sin(time * 0.5 + uSeed * 0.31)) * zoomPulse;
  uv = rot(time * (0.14 + uTwist * 0.34) + uSeed * 0.3) * uv;
  uv = domainWarp(uv, time, uWarp * 0.22);

  vec3 fillComposite = mix(uColorBg, uColorFg, 0.04 + uFill * 0.06);
  vec3 lineComposite = uColorBg;
  vec3 glowComposite = vec3(0.0);

  for (int i = 0; i < 3; i++) {
    float layerIndex = float(i);
    float layerScale = pow(max(uLayerSpread, 1.01), layerIndex);
    float speedScale = i == 0 ? 1.0 : (i == 1 ? PHI : 1.0 / PHI);
    float localTime = time * speedScale + layerIndex * 1.618;
    vec2 layerUv = rot(layerIndex * 0.55 + time * 0.03 * (layerIndex + 1.0)) * (uv * layerScale);
    vec3 layer = kaleidoscopeLayer(
      layerUv,
      localTime,
      max(uFolds, 3.0),
      max(uIters, 1.0),
      uScale,
      uLineWidth,
      uGlow,
      uWarp,
      uTwist,
      uFill
    );

    vec3 tint;
    if (uColorMode < 0.5) {
      tint = uColorFg;
    } else {
      float ang = atan(layerUv.y, layerUv.x);
      tint = 0.5 + 0.5 * cos(
        TAU * (vec3(0.0, 0.33, 0.67) + layerIndex * 0.1459 + ang / TAU + localTime * 0.22 + uSeed * 0.17)
      );
      tint = mix(uColorFg, tint, 0.78);
    }

    vec3 fillTint = mix(tint, screenBlend(tint, vec3(1.0)), 0.18 + layerIndex * 0.12);
    float opacity = pow(1.0 - layerIndex * 0.22, 0.7);

    fillComposite = mix(fillComposite, fillTint, layer.z * opacity * 0.95);
    lineComposite = mix(lineComposite, tint, layer.x * opacity);
    glowComposite = screenBlend(glowComposite, tint * layer.y * uGlow * 0.55 * opacity);
  }

  vec3 color = screenBlend(fillComposite, lineComposite);
  color = screenBlend(color, glowComposite);
  color = pow(color, vec3(max(uContrast, 0.65)));

  float vignette = 1.0 - (0.18 + uGlow * 0.06) * length(vUv - 0.5);
  color *= vignette;

  if (uStrobeRate > 0.01) {
    float sp = fract(uTime * uStrobeRate);
    float env = 1.0 - step(uStrobeDuty, sp);
    color = mix(color, uStrobeColor, env);
  }

  float alpha = clamp(
    max(
      max(length(glowComposite) * 0.22, dot(lineComposite, vec3(0.3333)) * 0.65),
      dot(fillComposite, vec3(0.3333)) * 0.45
    ) * uOpacity,
    0.0,
    1.0
  );

  gl_FragColor = vec4(color, alpha);
}
`

function makeMaterial(seed: number) {
  const material = new THREE.ShaderMaterial({
    vertexShader: VERT,
    fragmentShader: FRAG,
    transparent: true,
    depthWrite: false,
    side: THREE.DoubleSide,
    uniforms: {
      uTime: { value: 0 },
      uFolds: { value: 7 },
      uIters: { value: 9 },
      uSpeed: { value: 0.12 },
      uZoom: { value: 2.2 },
      uScale: { value: 1.82 },
      uLineWidth: { value: 1.0 },
      uGlow: { value: 1.0 },
      uWarp: { value: 0.32 },
      uTwist: { value: 0.4 },
      uLayerSpread: { value: 1.62 },
      uContrast: { value: 1.1 },
      uPulse: { value: 0.18 },
      uFill: { value: 0.5 },
      uOpacity: { value: 1.0 },
      uSeed: { value: seed },
      uColorMode: { value: 1 },
      uColorFg: { value: new THREE.Color('#ffffff') },
      uColorBg: { value: new THREE.Color('#000000') },
      uResolution: { value: new THREE.Vector2(1920, 1080) },
      uStrobeRate: { value: 0 },
      uStrobeDuty: { value: 0.15 },
      uStrobeColor: { value: new THREE.Color('#ffffff') },
    },
  })
  ;(material as any).extensions = { derivatives: true }
  return material
}

function MandalaPlane({
  params,
  seed,
  depthIndex,
}: {
  params: MandalaParams
  seed: number
  depthIndex: number
}) {
  const meshRef = useRef<THREE.Mesh>(null)
  const material = useMemo(() => makeMaterial(seed), [seed])

  useFrame((state) => {
    const t = params.animate ? state.clock.elapsedTime : 0
    const depth = params.depth
    const scale = 8 + depthIndex * 1.8 + depth * 1.6

    const u = material.uniforms
    u.uTime.value = t
    u.uFolds.value = Math.max(params.folds, 3)
    u.uIters.value = params.iters
    u.uSpeed.value = params.speed
    u.uZoom.value = params.zoom
    u.uScale.value = params.scale
    u.uLineWidth.value = params.lineWidth
    u.uGlow.value = params.glow
    u.uWarp.value = params.warp
    u.uTwist.value = params.twist
    u.uLayerSpread.value = params.layerSpread
    u.uContrast.value = params.contrast
    u.uPulse.value = params.pulse
    u.uFill.value = params.fill
    u.uColorMode.value = params.colorMode === 'spectrum' ? 1 : 0
    u.uColorFg.value.set(params.colorFg)
    u.uColorBg.value.set(params.colorBg)
    u.uResolution.value.set(state.size.width, state.size.height)
    u.uStrobeRate.value = params.strobeRate
    u.uStrobeDuty.value = params.strobeDuty
    u.uStrobeColor.value.set(params.strobeColor)
    u.uOpacity.value = depthIndex === 1 ? 0.9 : 0.45 + params.depth * 0.25

    if (meshRef.current) {
      meshRef.current.scale.set(scale, scale, 1)
      meshRef.current.position.z = (depthIndex - 1.0) * (1.0 + depth * 2.4) + Math.sin(t * (0.14 + depthIndex * 0.05) + seed) * depth * 0.3
      meshRef.current.rotation.z = t * (0.03 + params.twist * 0.09) * (depthIndex % 2 === 0 ? 1 : -1) + seed * 0.8
      meshRef.current.rotation.x = (depthIndex - 1.0) * 0.12 + Math.sin(t * 0.11 + seed) * depth * 0.24
      meshRef.current.rotation.y = Math.cos(t * 0.09 + seed) * depth * 0.22
    }
  })

  return (
    <mesh ref={meshRef} material={material}>
      <planeGeometry args={[2, 2, 64, 64]} />
    </mesh>
  )
}

function ParticleField({ params }: { params: MandalaParams }) {
  const groupRef = useRef<THREE.Group>(null)
  const count = Math.round(1200 + params.particles * 3800)

  const particles = useMemo(() => {
    const positions = new Float32Array(count * 3)
    const colors = new Float32Array(count * 3)
    const colorA = new THREE.Color(params.colorFg)
    const colorB = new THREE.Color(params.colorBg)
    const mixed = new THREE.Color()

    for (let i = 0; i < count; i++) {
      const radius = 2.5 + Math.random() * (6 + params.depth * 10)
      const theta = Math.random() * Math.PI * 2
      const phi = Math.acos(2 * Math.random() - 1)
      const wobble = 0.35 + Math.random() * 0.65

      positions[i * 3] = Math.sin(phi) * Math.cos(theta) * radius * wobble
      positions[i * 3 + 1] = Math.sin(phi) * Math.sin(theta) * radius
      positions[i * 3 + 2] = Math.cos(phi) * radius * (0.6 + params.depth * 0.9)

      mixed.copy(colorA).lerp(colorB, Math.random() * 0.65)
      colors[i * 3] = mixed.r
      colors[i * 3 + 1] = mixed.g
      colors[i * 3 + 2] = mixed.b
    }

    return { positions, colors }
  }, [count, params.colorBg, params.colorFg, params.depth])

  useFrame((state) => {
    if (!groupRef.current) return
    const t = params.animate ? state.clock.elapsedTime : 0
    groupRef.current.rotation.y = t * (0.03 + params.speed * 0.18)
    groupRef.current.rotation.x = Math.sin(t * 0.17) * 0.22 * params.depth
    groupRef.current.position.z = -1.4
  })

  return (
    <group ref={groupRef}>
      <points>
        <bufferGeometry>
          <bufferAttribute
            attach="attributes-position"
            args={[particles.positions, 3]}
            count={particles.positions.length / 3}
          />
          <bufferAttribute
            attach="attributes-color"
            args={[particles.colors, 3]}
            count={particles.colors.length / 3}
          />
        </bufferGeometry>
        <pointsMaterial
          size={0.025 + params.particles * 0.055}
          sizeAttenuation
          transparent
          depthWrite={false}
          vertexColors
          opacity={0.22 + params.particles * 0.35}
          blending={THREE.AdditiveBlending}
        />
      </points>
    </group>
  )
}

function CameraRig({ params }: { params: MandalaParams }) {
  const { camera } = useThree()

  useFrame((state) => {
    const t = params.animate ? state.clock.elapsedTime : 0
    camera.position.x = Math.sin(t * 0.11) * params.depth * 0.9
    camera.position.y = Math.cos(t * 0.13) * params.depth * 0.6
    camera.position.z = 7.2 - params.depth * 1.6 + Math.sin(t * 0.07) * 0.22
    camera.lookAt(0, 0, 0)
  })

  return null
}

function MandalaScene({ params }: { params: MandalaParams }) {
  return (
    <>
      <color attach="background" args={[params.colorBg]} />
      <fog attach="fog" args={[params.colorBg, 5.5, 16]} />
      <CameraRig params={params} />
      <ParticleField params={params} />
      <MandalaPlane params={params} seed={0.15} depthIndex={0} />
      <MandalaPlane params={params} seed={1.35} depthIndex={1} />
      <MandalaPlane params={params} seed={2.45} depthIndex={2} />
      <EffectComposer enableNormalPass={false} multisampling={0}>
        <Bloom
          intensity={0.35 + params.bloom * 1.85}
          luminanceThreshold={0}
          luminanceSmoothing={0.7}
          mipmapBlur
        />
        <Noise opacity={0.01 + params.particles * 0.01} premultiply />
        <Vignette eskil={false} offset={0.08} darkness={0.75 + params.depth * 0.18} />
      </EffectComposer>
    </>
  )
}

export function MandalaCanvas({
  active,
  params,
}: {
  active: boolean
  params: MandalaParams
}) {
  return (
    <Canvas
      frameloop={active ? 'always' : 'never'}
      camera={{ position: [0, 0, 7], fov: 42, near: 0.1, far: 60 }}
      gl={{ antialias: true, alpha: false }}
      style={{ position: 'absolute', inset: 0 }}
    >
      <MandalaScene params={params} />
    </Canvas>
  )
}
