import type { TunnelParams } from '../TunnelCanvas'

// ─── Tab identifiers ──────────────────────────────────────────────
// `myset` is virtual — derived from favorites in chunk 10. All
// authored presets pin to one of the other tabs. For chunk 2 we
// migrate the existing 18 to `signature` and leave the other tabs
// empty until chunk 5 fills them.
export type TabId =
  | 'signature'
  | 'psychedelic'
  | 'kaleido'
  | 'cosmic'
  | 'rave'
  | 'glitch'
  | 'sacred'
  | 'chroma'
  | 'myset'

// ─── Tab order, labels, capability copy ───────────────────────────
// `TAB_ORDER` is the canonical left-to-right tab strip order
// (excluding `myset`, which only appears when the user has favorites
// — chunk 10). `TAB_LABELS` is the rendered tab text. `TAB_CAPABILITY_COPY`
// is the one-line description shown beneath the active tab in
// `PresetsPanel`. `FLASH_TABS` flags tabs that emit a ⚠ FLASH badge in
// the tab strip + capability line; chunks 9+ wire it into the actual
// flash gate.
export const TAB_ORDER: Exclude<TabId, 'myset'>[] = [
  'signature', 'psychedelic', 'kaleido', 'cosmic',
  'rave', 'glitch', 'sacred', 'chroma',
]

export const TAB_LABELS: Record<TabId, string> = {
  signature: 'SIGNATURE',
  psychedelic: 'PSYCHEDELIC',
  kaleido: 'KALEIDO',
  cosmic: 'COSMIC',
  rave: 'RAVE',
  glitch: 'GLITCH',
  sacred: 'SACRED',
  chroma: 'CHROMA',
  myset: 'MY SET',
}

export const TAB_CAPABILITY_COPY: Record<TabId, string> = {
  signature: "The instrument's anchor presets — broad strokes across every capability.",
  psychedelic: 'Liquid color, fractal drift, chromatic separation, hue-shift motion.',
  kaleido: 'Mirror geometry from 4-fold to 16-fold symmetry, sharp pattern cells.',
  cosmic: 'Deep palettes, slow helix twist, long fog depth, gentle wave.',
  rave: 'Strobe presets, high-contrast neon, pulse and rainbow modes.',
  glitch: 'Chromatic split, signal-collapse, invert-mode flash, broken pattern shifts.',
  sacred: 'Gold/jewel tones, slow rotation, diamond/cross/rings under heavy symmetry.',
  chroma: 'Pure color motion — continuous hue drift, no patterns, soft cell-blur.',
  myset: 'Your starred presets.',
}

export const FLASH_TABS: Set<TabId> = new Set(['rave', 'glitch'])

// ─── Preset shape ─────────────────────────────────────────────────
// The closing chip in the chip list will surface `paletteName`. All
// other chips are derived from `values` by the auto-chip rules in
// chunk 6, so authoring stays focused on the palette.
//
// `flashWarn` is required for tab === 'rave' | 'glitch' and for any
// preset whose strobeRate > 2 or chromatic > 0.4 (enforced by the
// schema test).
export type Preset = {
  id: string                          // `${tab}.${slug}`, kebab-case slug
  tab: Exclude<TabId, 'myset'>        // MY SET is virtual, derived from favorites
  name: string                        // 'Neon Cathedral'
  paletteName: string                 // 'Gold/Pearl' — closing chip in the chip list
  values: Partial<TunnelParams>
  flashWarn?: boolean                 // required for rave/glitch + bright-strobe / heavy-chroma presets
}

// ─── User-facing presets ──────────────────────────────────────────
// 96 presets across 8 tabs (12 per tab). Each preset is hand-tuned
// to fit its tab's vibe and exercise the engine capability the
// capability-copy line promises. The 18 legacy "all-signature"
// presets have been redistributed: SUNBURST/CHECKER/HYPNO/VORTEX/
// WARP/DOTS/LINES/CIRCUIT/DECO live on under SIGNATURE; JULIA/LAVA/
// MELT/DREAM moved to PSYCHEDELIC; COSMIC/ZEN/VOID moved to COSMIC;
// TRIBAL/DECO live on under SACRED; RETRO moved to RAVE.
export const PRESETS: Preset[] = [
  // ─── SIGNATURE (12) ─────────────────────────────────────────────
  // Lobby presets. Every capability appears once but nothing is
  // extreme. No strobe; minimal chromatic; light kaleido on a few.
  {
    id: 'signature.sunburst',
    tab: 'signature',
    name: 'Sunburst',
    paletteName: 'Bone/Ink',
    values: { rings: 30, density: 2, speed: 0.02, roll: 0.3 },
  },
  {
    id: 'signature.checker',
    tab: 'signature',
    name: 'Checker',
    paletteName: 'Pearl/Charcoal',
    values: {
      rings: 4,
      density: 8,
      speed: 0.05,
      roll: 0,
      patternA: 'checker',
      patternB: null,
      colorA: '#f4f4ee',
      colorB: '#1a1a1a',
    },
  },
  {
    id: 'signature.hypno',
    tab: 'signature',
    name: 'Hypno',
    paletteName: 'Bone/Ink',
    values: { rings: 2, density: 60, speed: 0.1, roll: 0.8 },
  },
  {
    id: 'signature.vortex',
    tab: 'signature',
    name: 'Vortex',
    paletteName: 'Bone/Ink',
    values: { rings: 20, density: 4, speed: 0.08, roll: 2, helix: 3 },
  },
  {
    id: 'signature.warp',
    tab: 'signature',
    name: 'Warp',
    paletteName: 'Bone/Ink',
    values: { rings: 8, density: 30, speed: 0.06, bend: 30, wobble: 1 },
  },
  {
    id: 'signature.dots',
    tab: 'signature',
    name: 'Dots',
    paletteName: 'Bone/Ink',
    values: {
      rings: 4,
      density: 4,
      patternA: 'dots',
      patternB: 'dot',
      colorA: '#ffffff',
      colorB: '#000000',
    },
  },
  {
    id: 'signature.lines',
    tab: 'signature',
    name: 'Lines',
    paletteName: 'Bone/Ink',
    values: { rings: 10, density: 2, patternA: 'hlines', patternB: 'vlines' },
  },
  {
    id: 'signature.circuit',
    tab: 'signature',
    name: 'Circuit',
    paletteName: 'Phosphor/Ink',
    values: {
      rings: 8,
      density: 8,
      patternA: 'grid',
      patternB: 'dot',
      colorA: '#00ff41',
      colorB: '#050a05',
      cellBlur: 0,
      speed: 0.03,
    },
  },
  {
    id: 'signature.first-light',
    tab: 'signature',
    name: 'First Light',
    paletteName: 'Cream/Slate',
    values: {
      rings: 6,
      density: 4,
      patternA: 'gradient',
      patternB: null,
      colorA: '#fff2c2',
      colorB: '#2c3340',
      speed: 0.018,
      hueShift: 0.3,
      cellBlur: 0.1,
    },
  },
  {
    id: 'signature.honest-helix',
    tab: 'signature',
    name: 'Honest Helix',
    paletteName: 'Pearl/Plum',
    values: {
      rings: 4,
      density: 6,
      patternA: 'spiral',
      patternB: 'spiral',
      colorA: '#f0eadf',
      colorB: '#3a1f44',
      speed: 0.022,
      helix: 1.5,
    },
  },
  {
    id: 'signature.soft-lattice',
    tab: 'signature',
    name: 'Soft Lattice',
    paletteName: 'Mist/Steel',
    values: {
      rings: 6,
      density: 8,
      patternA: 'cross',
      patternB: 'cross',
      colorA: '#dde4ec',
      colorB: '#36465a',
      speed: 0.02,
      kaleidoscope: 4,
      cellBlur: 0.12,
    },
  },
  {
    id: 'signature.fair-wheel',
    tab: 'signature',
    name: 'Fair Wheel',
    paletteName: 'Cream/Cobalt',
    values: {
      rings: 8,
      density: 6,
      patternA: 'diamond',
      patternB: null,
      colorA: '#f6efdc',
      colorB: '#0e3a8a',
      speed: 0.025,
      kaleidoscope: 6,
      chromatic: 0.08,
    },
  },

  // ─── PSYCHEDELIC (12) ───────────────────────────────────────────
  // Heavy fractal/marble/noise. Chromatic 0.2-0.5. HueShift 0.5-2.0.
  // Saturated palettes — no white/black.
  {
    id: 'psychedelic.julia',
    tab: 'psychedelic',
    name: 'Julia',
    paletteName: 'Ink/Cyan',
    values: {
      rings: 3,
      density: 4,
      patternA: 'fractal',
      patternB: 'fractal',
      colorA: '#0a1530',
      colorB: '#00e5ff',
      speed: 0.03,
      chromatic: 0.25,
      hueShift: 0.8,
    },
  },
  {
    id: 'psychedelic.lava',
    tab: 'psychedelic',
    name: 'Lava',
    paletteName: 'Lava/Sun',
    values: {
      rings: 2,
      density: 2,
      patternA: 'marble',
      patternB: 'noise',
      colorA: '#ff1a00',
      colorB: '#ffcc00',
      speed: 0.035,
      chromatic: 0.3,
      hueShift: 1.0,
    },
  },
  {
    id: 'psychedelic.melt',
    tab: 'psychedelic',
    name: 'Melt',
    paletteName: 'Magenta/Indigo',
    values: {
      rings: 4,
      density: 4,
      cellBlur: 0.35,
      patternA: 'noise',
      patternB: null,
      colorA: '#ff1493',
      colorB: '#1a0040',
      speed: 0.04,
      chromatic: 0.35,
      hueShift: 1.2,
    },
  },
  {
    id: 'psychedelic.dream',
    tab: 'psychedelic',
    name: 'Dream',
    paletteName: 'Cyan/Twilight',
    values: {
      rings: 2,
      density: 10,
      patternA: 'fractal',
      patternB: 'marble',
      colorA: '#00e5ff',
      colorB: '#2d1b4e',
      cellBlur: 0.25,
      speed: 0.025,
      roll: 0.5,
      chromatic: 0.22,
      hueShift: 0.7,
    },
  },
  {
    id: 'psychedelic.liquid-saints',
    tab: 'psychedelic',
    name: 'Liquid Saints',
    paletteName: 'Saffron/Violet',
    values: {
      rings: 3,
      density: 6,
      patternA: 'marble',
      patternB: 'marble',
      colorA: '#ffb000',
      colorB: '#5a2eb0',
      cellBlur: 0.3,
      speed: 0.028,
      hueShift: 1.5,
      chromatic: 0.2,
    },
  },
  {
    id: 'psychedelic.solar-bloom',
    tab: 'psychedelic',
    name: 'Solar Bloom',
    paletteName: 'Solar/Magenta',
    flashWarn: true,
    values: {
      rings: 4,
      density: 8,
      patternA: 'fractal',
      patternB: null,
      colorA: '#ff7700',
      colorB: '#ff00aa',
      speed: 0.035,
      chromatic: 0.4,
      hueShift: 1.8,
      cellBlur: 0.18,
    },
  },
  {
    id: 'psychedelic.acid-bath',
    tab: 'psychedelic',
    name: 'Acid Bath',
    paletteName: 'Lime/Magenta',
    values: {
      rings: 3,
      density: 5,
      patternA: 'noise',
      patternB: 'fractal',
      colorA: '#aaff00',
      colorB: '#ff00cc',
      speed: 0.045,
      chromatic: 0.35,
      hueShift: 2.0,
      cellBlur: 0.22,
    },
    flashWarn: true,
  },
  {
    id: 'psychedelic.fractal-hymn',
    tab: 'psychedelic',
    name: 'Fractal Hymn',
    paletteName: 'Ink/Aurora',
    values: {
      rings: 3,
      density: 4,
      patternA: 'fractal',
      patternB: 'fractal',
      colorA: '#0a0030',
      colorB: '#00ffaa',
      speed: 0.022,
      chromatic: 0.3,
      hueShift: 1.0,
      kaleidoscope: 4,
    },
  },
  {
    id: 'psychedelic.hue-tide',
    tab: 'psychedelic',
    name: 'Hue Tide',
    paletteName: 'Coral/Teal',
    values: {
      rings: 5,
      density: 8,
      patternA: 'marble',
      patternB: null,
      colorA: '#ff5577',
      colorB: '#00aabb',
      speed: 0.03,
      hueShift: 2.0,
      chromatic: 0.18,
      cellBlur: 0.28,
    },
  },
  {
    id: 'psychedelic.dripped-sun',
    tab: 'psychedelic',
    name: 'Dripped Sun',
    paletteName: 'Marigold/Plum',
    values: {
      rings: 2,
      density: 4,
      patternA: 'marble',
      patternB: 'gradient',
      colorA: '#ffa500',
      colorB: '#3a0066',
      speed: 0.026,
      cellBlur: 0.32,
      chromatic: 0.25,
      hueShift: 1.3,
    },
  },
  {
    id: 'psychedelic.chromatic-spill',
    tab: 'psychedelic',
    name: 'Chromatic Spill',
    paletteName: 'Cyan/Hot Pink',
    values: {
      rings: 4,
      density: 12,
      patternA: 'noise',
      patternB: 'noise',
      colorA: '#00ddff',
      colorB: '#ff2288',
      speed: 0.04,
      chromatic: 0.5,
      hueShift: 1.6,
      cellBlur: 0.15,
    },
    flashWarn: true,
  },
  {
    id: 'psychedelic.inner-eye',
    tab: 'psychedelic',
    name: 'Inner Eye',
    paletteName: 'Indigo/Saffron',
    values: {
      rings: 3,
      density: 4,
      patternA: 'fractal',
      patternB: 'radialGrad',
      colorA: '#1a0040',
      colorB: '#ffc107',
      speed: 0.02,
      chromatic: 0.28,
      hueShift: 0.9,
      cellBlur: 0.2,
      kaleidoscope: 6,
    },
  },

  // ─── KALEIDO (12) ────────────────────────────────────────────────
  // Kaleidoscope spans 4..16. Handed patterns. Sharp cell edges.
  {
    id: 'kaleido.temple-glass',
    tab: 'kaleido',
    name: 'Temple Glass',
    paletteName: 'Cobalt/Gold',
    values: {
      rings: 6,
      density: 8,
      patternA: 'diagonal',
      patternB: 'diagonal',
      colorA: '#1a3a8a',
      colorB: '#ffc844',
      kaleidoscope: 4,
      speed: 0.025,
      cellBlur: 0.05,
    },
  },
  {
    id: 'kaleido.twelve-petals',
    tab: 'kaleido',
    name: 'Twelve Petals',
    paletteName: 'Rose/Cream',
    values: {
      rings: 8,
      density: 6,
      patternA: 'spiral',
      patternB: 'spiral',
      colorA: '#ff5588',
      colorB: '#fff4dd',
      kaleidoscope: 12,
      speed: 0.028,
      cellBlur: 0,
    },
  },
  {
    id: 'kaleido.stained-hex',
    tab: 'kaleido',
    name: 'Stained Hex',
    paletteName: 'Ruby/Cobalt',
    values: {
      rings: 4,
      density: 6,
      patternA: 'cross',
      patternB: 'cross',
      colorA: '#cc1133',
      colorB: '#1144aa',
      kaleidoscope: 6,
      speed: 0.022,
      cellBlur: 0.04,
    },
  },
  {
    id: 'kaleido.octagon-shrine',
    tab: 'kaleido',
    name: 'Octagon Shrine',
    paletteName: 'Pearl/Emerald',
    values: {
      rings: 6,
      density: 8,
      patternA: 'diamond',
      patternB: 'diamond',
      colorA: '#f0f0e8',
      colorB: '#0e6b48',
      kaleidoscope: 8,
      speed: 0.024,
      cellBlur: 0,
    },
  },
  {
    id: 'kaleido.hex-cathedral',
    tab: 'kaleido',
    name: 'Hex Cathedral',
    paletteName: 'Violet/Gold',
    values: {
      rings: 8,
      density: 10,
      patternA: 'fractal',
      patternB: 'cross',
      colorA: '#4a1a8a',
      colorB: '#ffd166',
      kaleidoscope: 6,
      speed: 0.02,
      cellBlur: 0.08,
    },
  },
  {
    id: 'kaleido.sixteen-fold',
    tab: 'kaleido',
    name: 'Sixteen-Fold',
    paletteName: 'Ink/Aqua',
    values: {
      rings: 10,
      density: 12,
      patternA: 'diagonal',
      patternB: 'cross',
      colorA: '#0a1020',
      colorB: '#22e2c8',
      kaleidoscope: 16,
      speed: 0.018,
      cellBlur: 0.02,
    },
  },
  {
    id: 'kaleido.quad-mirror',
    tab: 'kaleido',
    name: 'Quad Mirror',
    paletteName: 'Bone/Coral',
    values: {
      rings: 4,
      density: 4,
      patternA: 'spiral',
      patternB: null,
      colorA: '#f4eee4',
      colorB: '#ff6655',
      kaleidoscope: 4,
      speed: 0.03,
      cellBlur: 0,
    },
  },
  {
    id: 'kaleido.dodec-spin',
    tab: 'kaleido',
    name: 'Dodec Spin',
    paletteName: 'Charcoal/Lemon',
    values: {
      rings: 6,
      density: 8,
      patternA: 'fractal',
      patternB: 'fractal',
      colorA: '#1a1a22',
      colorB: '#fff158',
      kaleidoscope: 12,
      speed: 0.026,
      roll: 0.6,
      cellBlur: 0.05,
    },
  },
  {
    id: 'kaleido.petal-storm',
    tab: 'kaleido',
    name: 'Petal Storm',
    paletteName: 'Magenta/Mint',
    values: {
      rings: 8,
      density: 10,
      patternA: 'spiral',
      patternB: 'cross',
      colorA: '#ee2288',
      colorB: '#aaffd0',
      kaleidoscope: 10,
      speed: 0.032,
      cellBlur: 0,
    },
  },
  {
    id: 'kaleido.glass-wheel',
    tab: 'kaleido',
    name: 'Glass Wheel',
    paletteName: 'Sky/Sunset',
    values: {
      rings: 5,
      density: 6,
      patternA: 'diagonal',
      patternB: 'diamond',
      colorA: '#88ccff',
      colorB: '#ff7733',
      kaleidoscope: 8,
      speed: 0.024,
      cellBlur: 0.04,
    },
  },
  {
    id: 'kaleido.crystal-lattice',
    tab: 'kaleido',
    name: 'Crystal Lattice',
    paletteName: 'Pearl/Onyx',
    values: {
      rings: 12,
      density: 12,
      patternA: 'cross',
      patternB: 'diagonal',
      colorA: '#ece8d8',
      colorB: '#080812',
      kaleidoscope: 14,
      speed: 0.022,
      cellBlur: 0,
    },
  },
  {
    id: 'kaleido.mandala-drift',
    tab: 'kaleido',
    name: 'Mandala Drift',
    paletteName: 'Saffron/Ink',
    values: {
      rings: 6,
      density: 8,
      patternA: 'spiral',
      patternB: 'fractal',
      colorA: '#ffa800',
      colorB: '#0a0a18',
      kaleidoscope: 10,
      speed: 0.02,
      roll: 0.4,
      cellBlur: 0.06,
    },
  },

  // ─── COSMIC (12) ────────────────────────────────────────────────
  // Slow speed (0.005-0.025). Deep helix (1-4). Long fogFar (60-100).
  // Subtle wave. Dark palettes. No strobe.
  {
    id: 'cosmic.cosmic-classic',
    tab: 'cosmic',
    name: 'Cosmic',
    paletteName: 'Velvet/Gold',
    values: {
      rings: 3,
      density: 4,
      patternA: 'radialGrad',
      patternB: 'spiral',
      colorA: '#1a0e3a',
      colorB: '#ffd700',
      cellBlur: 0.18,
      speed: 0.018,
      helix: 1.5,
      fogFar: 70,
      wave: 0.5,
    },
  },
  {
    id: 'cosmic.zen',
    tab: 'cosmic',
    name: 'Zen',
    paletteName: 'Pearl/Deep Sea',
    values: {
      rings: 6,
      density: 2,
      patternA: 'spiral',
      patternB: 'radialGrad',
      colorA: '#dde6ee',
      colorB: '#0a1f2f',
      speed: 0.01,
      roll: 0.1,
      fogFar: 80,
      cellBlur: 0.18,
    },
  },
  {
    id: 'cosmic.void',
    tab: 'cosmic',
    name: 'Void',
    paletteName: 'Onyx/Charcoal',
    values: {
      rings: 20,
      density: 2,
      cellBlur: 0.4,
      colorA: '#000000',
      colorB: '#0e1018',
      speed: 0.008,
      roll: 0.6,
      helix: 2,
      fogFar: 100,
    },
  },
  {
    id: 'cosmic.deep-orbit',
    tab: 'cosmic',
    name: 'Deep Orbit',
    paletteName: 'Indigo/Star',
    values: {
      rings: 4,
      density: 6,
      patternA: 'radialGrad',
      patternB: null,
      colorA: '#0a1240',
      colorB: '#a8c4ff',
      speed: 0.012,
      helix: 2.5,
      fogFar: 90,
      wave: 0.7,
      cellBlur: 0.22,
    },
  },
  {
    id: 'cosmic.slow-nova',
    tab: 'cosmic',
    name: 'Slow Nova',
    paletteName: 'Plum/Ember',
    values: {
      rings: 3,
      density: 4,
      patternA: 'gradient',
      patternB: 'radialGrad',
      colorA: '#22102f',
      colorB: '#ff7733',
      speed: 0.009,
      helix: 1.2,
      fogFar: 75,
      kaleidoscope: 6,
      cellBlur: 0.2,
    },
  },
  {
    id: 'cosmic.black-lotus',
    tab: 'cosmic',
    name: 'Black Lotus',
    paletteName: 'Onyx/Lotus',
    values: {
      rings: 6,
      density: 8,
      patternA: 'spiral',
      patternB: 'spiral',
      colorA: '#08080e',
      colorB: '#cc7799',
      speed: 0.014,
      helix: 1.8,
      kaleidoscope: 8,
      fogFar: 70,
      cellBlur: 0.15,
    },
  },
  {
    id: 'cosmic.outer-spiral',
    tab: 'cosmic',
    name: 'Outer Spiral',
    paletteName: 'Navy/Pearl',
    values: {
      rings: 5,
      density: 6,
      patternA: 'spiral',
      patternB: null,
      colorA: '#0a1830',
      colorB: '#e8eef8',
      speed: 0.02,
      helix: 3,
      fogFar: 85,
      wave: 0.4,
      cellBlur: 0.1,
    },
  },
  {
    id: 'cosmic.long-fall',
    tab: 'cosmic',
    name: 'Long Fall',
    paletteName: 'Ink/Cyan Pulse',
    values: {
      rings: 2,
      density: 4,
      patternA: 'gradient',
      patternB: null,
      colorA: '#000810',
      colorB: '#1a8eaa',
      speed: 0.025,
      helix: 4,
      fogFar: 100,
      cellBlur: 0.25,
    },
  },
  {
    id: 'cosmic.helix-drift',
    tab: 'cosmic',
    name: 'Helix Drift',
    paletteName: 'Charcoal/Mint',
    values: {
      rings: 4,
      density: 8,
      patternA: 'spiral',
      patternB: 'cross',
      colorA: '#15181f',
      colorB: '#88e0c0',
      speed: 0.016,
      helix: 2.2,
      wave: 0.8,
      fogFar: 75,
      cellBlur: 0.12,
    },
  },
  {
    id: 'cosmic.comet-bath',
    tab: 'cosmic',
    name: 'Comet Bath',
    paletteName: 'Midnight/Ice',
    values: {
      rings: 3,
      density: 4,
      patternA: 'marble',
      patternB: null,
      colorA: '#0a0e2a',
      colorB: '#9adfff',
      speed: 0.01,
      helix: 1,
      wave: 1,
      fogFar: 80,
      cellBlur: 0.3,
      hueShift: 0.4,
    },
  },
  {
    id: 'cosmic.eclipse',
    tab: 'cosmic',
    name: 'Eclipse',
    paletteName: 'Onyx/Solar',
    values: {
      rings: 12,
      density: 4,
      patternA: 'radialGrad',
      patternB: null,
      colorA: '#000000',
      colorB: '#ff8a00',
      speed: 0.006,
      helix: 0.8,
      fogFar: 95,
      kaleidoscope: 4,
      cellBlur: 0.2,
    },
  },
  {
    id: 'cosmic.outer-ring',
    tab: 'cosmic',
    name: 'Outer Ring',
    paletteName: 'Ink/Lavender',
    values: {
      rings: 16,
      density: 6,
      patternA: 'rings',
      patternB: null,
      colorA: '#08081a',
      colorB: '#b8a0e8',
      speed: 0.012,
      helix: 1.5,
      fogFar: 85,
      cellBlur: 0.18,
    },
  },

  // ─── RAVE (12) ───────────────────────────────────────────────────
  // strobeRate > 0 on every preset. Mix of strobeMode 0..4. High contrast.
  // Faster speed. flashWarn true for all.
  {
    id: 'rave.retro',
    tab: 'rave',
    name: 'Retro',
    paletteName: 'Hot Pink/Cyan',
    values: {
      rings: 6,
      density: 6,
      patternA: 'checker',
      patternB: 'checker',
      colorA: '#ff1493',
      colorB: '#00e1ff',
      strobeRate: 4,
      strobeDuty: 0.3,
      strobeMode: 0,
      strobeColor: '#ffffff',
      speed: 0.05,
    },
    flashWarn: true,
  },
  {
    id: 'rave.neon-cathedral',
    tab: 'rave',
    name: 'Neon Cathedral',
    paletteName: 'Magenta/Lime',
    values: {
      rings: 8,
      density: 8,
      patternA: 'diamond',
      patternB: 'cross',
      colorA: '#ff00aa',
      colorB: '#88ff00',
      strobeRate: 5,
      strobeDuty: 0.25,
      strobeMode: 1,
      strobeColor: '#ffffff',
      speed: 0.06,
      kaleidoscope: 6,
    },
    flashWarn: true,
  },
  {
    id: 'rave.police-line',
    tab: 'rave',
    name: 'Police Line',
    paletteName: 'Cobalt/Crimson',
    values: {
      rings: 4,
      density: 4,
      patternA: 'checker',
      patternB: null,
      colorA: '#0044ff',
      colorB: '#ff0022',
      strobeRate: 3,
      strobeDuty: 0.4,
      strobeMode: 3,
      strobeColor: '#ffffff',
      speed: 0.05,
    },
    flashWarn: true,
  },
  {
    id: 'rave.chrome-fever',
    tab: 'rave',
    name: 'Chrome Fever',
    paletteName: 'Silver/Hot Pink',
    values: {
      rings: 6,
      density: 12,
      patternA: 'diagonal',
      patternB: 'diagonal',
      colorA: '#dadada',
      colorB: '#ff2288',
      strobeRate: 6,
      strobeDuty: 0.2,
      strobeMode: 0,
      strobeColor: '#ff00ff',
      speed: 0.07,
      chromatic: 0.2,
    },
    flashWarn: true,
  },
  {
    id: 'rave.pulse-cathedral',
    tab: 'rave',
    name: 'Pulse Cathedral',
    paletteName: 'Violet/Acid',
    values: {
      rings: 8,
      density: 6,
      patternA: 'spiral',
      patternB: 'cross',
      colorA: '#5a00aa',
      colorB: '#aaff00',
      strobeRate: 2.5,
      strobeDuty: 0.5,
      strobeMode: 1,
      strobeColor: '#ffffff',
      kaleidoscope: 8,
      speed: 0.05,
    },
    flashWarn: true,
  },
  {
    id: 'rave.rave-saint',
    tab: 'rave',
    name: 'Rave Saint',
    paletteName: 'Ink/Solar',
    values: {
      rings: 4,
      density: 8,
      patternA: 'fractal',
      patternB: null,
      colorA: '#0a0010',
      colorB: '#ff8800',
      strobeRate: 4,
      strobeDuty: 0.3,
      strobeMode: 2,
      strobeColor: '#ffffff',
      speed: 0.06,
      hueShift: 1.5,
    },
    flashWarn: true,
  },
  {
    id: 'rave.strobe-sun',
    tab: 'rave',
    name: 'Strobe Sun',
    paletteName: 'Solar/Crimson',
    values: {
      rings: 30,
      density: 2,
      colorA: '#ffd200',
      colorB: '#cc0033',
      strobeRate: 5,
      strobeDuty: 0.2,
      strobeMode: 0,
      strobeColor: '#ffffff',
      speed: 0.08,
      roll: 1.5,
    },
    flashWarn: true,
  },
  {
    id: 'rave.hot-mirror',
    tab: 'rave',
    name: 'Hot Mirror',
    paletteName: 'Magenta/Cyan',
    values: {
      rings: 6,
      density: 8,
      patternA: 'diagonal',
      patternB: 'cross',
      colorA: '#ff0088',
      colorB: '#00ddff',
      strobeRate: 3,
      strobeDuty: 0.3,
      strobeMode: 4,
      strobeColor: '#ffffff',
      kaleidoscope: 6,
      speed: 0.06,
    },
    flashWarn: true,
  },
  {
    id: 'rave.acid-strobe',
    tab: 'rave',
    name: 'Acid Strobe',
    paletteName: 'Acid Lime/Magenta',
    values: {
      rings: 4,
      density: 6,
      patternA: 'checker',
      patternB: 'checker',
      colorA: '#aaff00',
      colorB: '#ff00cc',
      strobeRate: 7,
      strobeDuty: 0.2,
      strobeMode: 0,
      strobeColor: '#aaff00',
      speed: 0.08,
    },
    flashWarn: true,
  },
  {
    id: 'rave.mosh-rainbow',
    tab: 'rave',
    name: 'Mosh Rainbow',
    paletteName: 'Spectrum/Ink',
    values: {
      rings: 8,
      density: 10,
      patternA: 'fractal',
      patternB: null,
      colorA: '#0a0a0a',
      colorB: '#ffffff',
      strobeRate: 4,
      strobeDuty: 0.5,
      strobeMode: 2,
      speed: 0.07,
      hueShift: 2.0,
      chromatic: 0.25,
    },
    flashWarn: true,
  },
  {
    id: 'rave.pulse-hex',
    tab: 'rave',
    name: 'Pulse Hex',
    paletteName: 'Cobalt/Lemon',
    values: {
      rings: 6,
      density: 12,
      patternA: 'cross',
      patternB: 'diamond',
      colorA: '#1144cc',
      colorB: '#fff200',
      strobeRate: 3.5,
      strobeDuty: 0.4,
      strobeMode: 1,
      strobeColor: '#ffffff',
      kaleidoscope: 6,
      speed: 0.055,
    },
    flashWarn: true,
  },
  {
    id: 'rave.rainbow-riot',
    tab: 'rave',
    name: 'Rainbow Riot',
    paletteName: 'Spectrum',
    values: {
      rings: 4,
      density: 8,
      patternA: 'spiral',
      patternB: 'spiral',
      colorA: '#ff0000',
      colorB: '#0000ff',
      strobeRate: 6,
      strobeDuty: 0.5,
      strobeMode: 2,
      speed: 0.09,
      hueShift: 2.5,
    },
    flashWarn: true,
  },

  // ─── GLITCH (12) ─────────────────────────────────────────────────
  // Heavy chromatic (0.3-0.8). Some invert mode. Fast speed. Aggressive
  // patterns. flashWarn true for all.
  {
    id: 'glitch.signal-collapse',
    tab: 'glitch',
    name: 'Signal Collapse',
    paletteName: 'Phosphor/Black',
    values: {
      rings: 4,
      density: 8,
      patternA: 'hlines',
      patternB: 'noise',
      colorA: '#00ff41',
      colorB: '#000000',
      chromatic: 0.6,
      speed: 0.08,
      strobeRate: 2,
      strobeDuty: 0.3,
      strobeMode: 4,
      strobeColor: '#ffffff',
    },
    flashWarn: true,
  },
  {
    id: 'glitch.opal-circuit',
    tab: 'glitch',
    name: 'Opal Circuit',
    paletteName: 'Cyan/Magenta',
    values: {
      rings: 8,
      density: 12,
      patternA: 'grid',
      patternB: 'fractal',
      colorA: '#00e0ff',
      colorB: '#ff00aa',
      chromatic: 0.55,
      speed: 0.06,
      hueShift: 1.0,
    },
    flashWarn: true,
  },
  {
    id: 'glitch.broken-channel',
    tab: 'glitch',
    name: 'Broken Channel',
    paletteName: 'Red/Aqua',
    values: {
      rings: 4,
      density: 6,
      patternA: 'vlines',
      patternB: 'hlines',
      colorA: '#ff2200',
      colorB: '#00eed0',
      chromatic: 0.7,
      speed: 0.1,
      strobeRate: 1.5,
      strobeDuty: 0.2,
      strobeMode: 4,
    },
    flashWarn: true,
  },
  {
    id: 'glitch.drift-error',
    tab: 'glitch',
    name: 'Drift Error',
    paletteName: 'Ink/Phosphor',
    values: {
      rings: 6,
      density: 4,
      patternA: 'noise',
      patternB: 'cross',
      colorA: '#0a0a0a',
      colorB: '#22ff88',
      chromatic: 0.4,
      speed: 0.07,
      hueShift: 1.5,
      cellBlur: 0.1,
    },
    flashWarn: true,
  },
  {
    id: 'glitch.chrome-bleed',
    tab: 'glitch',
    name: 'Chrome Bleed',
    paletteName: 'Pearl/Magenta',
    values: {
      rings: 3,
      density: 4,
      patternA: 'gradient',
      patternB: 'noise',
      colorA: '#f0f0e8',
      colorB: '#ee0066',
      chromatic: 0.8,
      speed: 0.05,
      cellBlur: 0.2,
    },
    flashWarn: true,
  },
  {
    id: 'glitch.channel-tear',
    tab: 'glitch',
    name: 'Channel Tear',
    paletteName: 'Red/Cyan/Lime',
    values: {
      rings: 8,
      density: 8,
      patternA: 'hlines',
      patternB: 'vlines',
      colorA: '#ff0033',
      colorB: '#00ddee',
      chromatic: 0.65,
      speed: 0.12,
      strobeRate: 3,
      strobeDuty: 0.3,
      strobeMode: 4,
    },
    flashWarn: true,
  },
  {
    id: 'glitch.static-storm',
    tab: 'glitch',
    name: 'Static Storm',
    paletteName: 'Snow/Ink',
    values: {
      rings: 4,
      density: 16,
      patternA: 'noise',
      patternB: 'noise',
      colorA: '#e8e8e8',
      colorB: '#101010',
      chromatic: 0.45,
      speed: 0.15,
      strobeRate: 5,
      strobeDuty: 0.2,
      strobeMode: 0,
      strobeColor: '#ffffff',
    },
    flashWarn: true,
  },
  {
    id: 'glitch.signal-saint',
    tab: 'glitch',
    name: 'Signal Saint',
    paletteName: 'Acid/Amethyst',
    values: {
      rings: 6,
      density: 10,
      patternA: 'fractal',
      patternB: 'grid',
      colorA: '#aaff00',
      colorB: '#7733cc',
      chromatic: 0.5,
      speed: 0.08,
      hueShift: 1.8,
      kaleidoscope: 4,
    },
    flashWarn: true,
  },
  {
    id: 'glitch.frame-skip',
    tab: 'glitch',
    name: 'Frame Skip',
    paletteName: 'White/Hot Pink',
    values: {
      rings: 4,
      density: 6,
      patternA: 'checker',
      patternB: 'noise',
      colorA: '#ffffff',
      colorB: '#ff1166',
      chromatic: 0.55,
      speed: 0.09,
      strobeRate: 4,
      strobeDuty: 0.15,
      strobeMode: 0,
      strobeColor: '#000000',
    },
    flashWarn: true,
  },
  {
    id: 'glitch.drift-channel',
    tab: 'glitch',
    name: 'Drift Channel',
    paletteName: 'Sapphire/Coral',
    values: {
      rings: 5,
      density: 8,
      patternA: 'gradient',
      patternB: 'hlines',
      colorA: '#1133aa',
      colorB: '#ff8866',
      chromatic: 0.45,
      speed: 0.06,
      hueShift: 0.8,
      cellBlur: 0.12,
    },
    flashWarn: true,
  },
  {
    id: 'glitch.hex-crash',
    tab: 'glitch',
    name: 'Hex Crash',
    paletteName: 'Ink/Lemon',
    values: {
      rings: 8,
      density: 12,
      patternA: 'cross',
      patternB: 'fractal',
      colorA: '#080814',
      colorB: '#fff033',
      chromatic: 0.6,
      speed: 0.08,
      kaleidoscope: 6,
      strobeRate: 2.5,
      strobeDuty: 0.3,
      strobeMode: 4,
    },
    flashWarn: true,
  },
  {
    id: 'glitch.color-tear',
    tab: 'glitch',
    name: 'Color Tear',
    paletteName: 'Hot Pink/Cyan',
    values: {
      rings: 4,
      density: 6,
      patternA: 'diagonal',
      patternB: null,
      colorA: '#ff1188',
      colorB: '#00cce0',
      chromatic: 0.75,
      speed: 0.07,
      hueShift: 1.2,
    },
    flashWarn: true,
  },

  // ─── SACRED (12) ─────────────────────────────────────────────────
  // Slow speed. High kaleidoscope (8-16). Diamond/cross/rings.
  // Gold/jewel palettes. Soft cellBlur. No strobe.
  {
    id: 'sacred.tribal',
    tab: 'sacred',
    name: 'Tribal',
    paletteName: 'Gold/Velvet',
    values: {
      rings: 6,
      density: 6,
      patternA: 'diagonal',
      patternB: 'diagonal',
      colorA: '#ffcc00',
      colorB: '#4a0e60',
      kaleidoscope: 8,
      speed: 0.018,
      cellBlur: 0.12,
    },
  },
  {
    id: 'sacred.deco',
    tab: 'sacred',
    name: 'Deco',
    paletteName: 'Gold/Black',
    values: {
      rings: 4,
      density: 4,
      patternA: 'diamond',
      patternB: 'cross',
      colorA: '#ffd700',
      colorB: '#000000',
      kaleidoscope: 8,
      speed: 0.015,
      cellBlur: 0.1,
    },
  },
  {
    id: 'sacred.gold-vesica',
    tab: 'sacred',
    name: 'Gold Vesica',
    paletteName: 'Gold/Ink',
    values: {
      rings: 12,
      density: 8,
      patternA: 'rings',
      patternB: 'diamond',
      colorA: '#ffc94a',
      colorB: '#0a0a0e',
      kaleidoscope: 12,
      speed: 0.012,
      cellBlur: 0.18,
    },
  },
  {
    id: 'sacred.sun-wheel',
    tab: 'sacred',
    name: 'Sun Wheel',
    paletteName: 'Solar/Cobalt',
    values: {
      rings: 8,
      density: 10,
      patternA: 'cross',
      patternB: 'diamond',
      colorA: '#ffae00',
      colorB: '#0e2a8a',
      kaleidoscope: 16,
      speed: 0.02,
      cellBlur: 0.15,
    },
  },
  {
    id: 'sacred.orphic-petal',
    tab: 'sacred',
    name: 'Orphic Petal',
    paletteName: 'Copper/Violet',
    values: {
      rings: 6,
      density: 6,
      patternA: 'diamond',
      patternB: 'spiral',
      colorA: '#cc6633',
      colorB: '#552288',
      kaleidoscope: 10,
      speed: 0.014,
      cellBlur: 0.2,
    },
  },
  {
    id: 'sacred.temple-bloom',
    tab: 'sacred',
    name: 'Temple Bloom',
    paletteName: 'Saffron/Emerald',
    values: {
      rings: 10,
      density: 8,
      patternA: 'rings',
      patternB: 'cross',
      colorA: '#f4a020',
      colorB: '#0a5544',
      kaleidoscope: 12,
      speed: 0.012,
      cellBlur: 0.22,
    },
  },
  {
    id: 'sacred.quiet-halo',
    tab: 'sacred',
    name: 'Quiet Halo',
    paletteName: 'Pearl/Bronze',
    values: {
      rings: 16,
      density: 4,
      patternA: 'rings',
      patternB: null,
      colorA: '#f4ecd6',
      colorB: '#aa7733',
      kaleidoscope: 8,
      speed: 0.008,
      cellBlur: 0.3,
    },
  },
  {
    id: 'sacred.slow-sun',
    tab: 'sacred',
    name: 'Slow Sun',
    paletteName: 'Honey/Ink',
    values: {
      rings: 8,
      density: 6,
      patternA: 'diamond',
      patternB: 'rings',
      colorA: '#ffb83a',
      colorB: '#1a1208',
      kaleidoscope: 12,
      speed: 0.01,
      cellBlur: 0.16,
    },
  },
  {
    id: 'sacred.long-cathedral',
    tab: 'sacred',
    name: 'Long Cathedral',
    paletteName: 'Cobalt/Gold',
    values: {
      rings: 12,
      density: 8,
      patternA: 'cross',
      patternB: 'rings',
      colorA: '#10248a',
      colorB: '#f4c14a',
      kaleidoscope: 16,
      speed: 0.012,
      cellBlur: 0.18,
      fogFar: 60,
    },
  },
  {
    id: 'sacred.honey-glass',
    tab: 'sacred',
    name: 'Honey Glass',
    paletteName: 'Amber/Pearl',
    values: {
      rings: 6,
      density: 8,
      patternA: 'diamond',
      patternB: 'cross',
      colorA: '#e89c1a',
      colorB: '#fff4dc',
      kaleidoscope: 10,
      speed: 0.016,
      cellBlur: 0.14,
    },
  },
  {
    id: 'sacred.vesica-drift',
    tab: 'sacred',
    name: 'Vesica Drift',
    paletteName: 'Rose Gold/Plum',
    values: {
      rings: 10,
      density: 6,
      patternA: 'rings',
      patternB: 'diamond',
      colorA: '#dd9a88',
      colorB: '#3a1844',
      kaleidoscope: 12,
      speed: 0.013,
      cellBlur: 0.22,
      hueShift: 0.3,
    },
  },
  {
    id: 'sacred.old-halo',
    tab: 'sacred',
    name: 'Old Halo',
    paletteName: 'Bronze/Onyx',
    values: {
      rings: 14,
      density: 4,
      patternA: 'rings',
      patternB: 'cross',
      colorA: '#a87c44',
      colorB: '#080808',
      kaleidoscope: 14,
      speed: 0.009,
      cellBlur: 0.25,
    },
  },

  // ─── CHROMA (12) ─────────────────────────────────────────────────
  // Pure color motion. patternA/B null on most. Heavy hueShift (1.0-3.0).
  // Soft cellBlur (0.3-0.5). No strobe.
  {
    id: 'chroma.hue-drift',
    tab: 'chroma',
    name: 'Hue Drift',
    paletteName: 'Magenta/Cyan',
    values: {
      rings: 4,
      density: 4,
      patternA: null,
      patternB: null,
      colorA: '#ff2288',
      colorB: '#22ddee',
      hueShift: 1.5,
      cellBlur: 0.4,
      speed: 0.025,
    },
  },
  {
    id: 'chroma.blacklight-garden',
    tab: 'chroma',
    name: 'Blacklight Garden',
    paletteName: 'Violet/Acid',
    values: {
      rings: 6,
      density: 4,
      patternA: null,
      patternB: null,
      colorA: '#3300aa',
      colorB: '#aaff00',
      hueShift: 2.0,
      cellBlur: 0.45,
      speed: 0.03,
      kaleidoscope: 6,
    },
  },
  {
    id: 'chroma.color-sermon',
    tab: 'chroma',
    name: 'Color Sermon',
    paletteName: 'Saffron/Sea',
    values: {
      rings: 3,
      density: 4,
      patternA: null,
      patternB: null,
      colorA: '#f4a020',
      colorB: '#0a8aaa',
      hueShift: 1.2,
      cellBlur: 0.5,
      speed: 0.02,
    },
  },
  {
    id: 'chroma.pure-bleed',
    tab: 'chroma',
    name: 'Pure Bleed',
    paletteName: 'Hot Pink/Indigo',
    values: {
      rings: 2,
      density: 4,
      patternA: null,
      patternB: null,
      colorA: '#ff0088',
      colorB: '#1a0066',
      hueShift: 2.4,
      cellBlur: 0.5,
      speed: 0.035,
    },
  },
  {
    id: 'chroma.soft-drift',
    tab: 'chroma',
    name: 'Soft Drift',
    paletteName: 'Mint/Lilac',
    values: {
      rings: 4,
      density: 6,
      patternA: null,
      patternB: null,
      colorA: '#aae8c8',
      colorB: '#cca8e8',
      hueShift: 1.0,
      cellBlur: 0.45,
      speed: 0.018,
    },
  },
  {
    id: 'chroma.cool-bath',
    tab: 'chroma',
    name: 'Cool Bath',
    paletteName: 'Aqua/Sapphire',
    values: {
      rings: 5,
      density: 4,
      patternA: null,
      patternB: null,
      colorA: '#22ccff',
      colorB: '#0044aa',
      hueShift: 1.4,
      cellBlur: 0.4,
      speed: 0.02,
      kaleidoscope: 4,
    },
  },
  {
    id: 'chroma.warm-bath',
    tab: 'chroma',
    name: 'Warm Bath',
    paletteName: 'Coral/Marigold',
    values: {
      rings: 5,
      density: 4,
      patternA: null,
      patternB: null,
      colorA: '#ff7755',
      colorB: '#ffc844',
      hueShift: 1.4,
      cellBlur: 0.4,
      speed: 0.02,
      kaleidoscope: 4,
    },
  },
  {
    id: 'chroma.long-spectrum',
    tab: 'chroma',
    name: 'Long Spectrum',
    paletteName: 'Spectrum',
    values: {
      rings: 8,
      density: 6,
      patternA: null,
      patternB: null,
      colorA: '#ff0000',
      colorB: '#00ff00',
      hueShift: 3.0,
      cellBlur: 0.35,
      speed: 0.025,
    },
  },
  {
    id: 'chroma.slow-wash',
    tab: 'chroma',
    name: 'Slow Wash',
    paletteName: 'Cream/Rose',
    values: {
      rings: 3,
      density: 4,
      patternA: null,
      patternB: null,
      colorA: '#fff0d8',
      colorB: '#ee9aaa',
      hueShift: 1.0,
      cellBlur: 0.5,
      speed: 0.012,
    },
  },
  {
    id: 'chroma.pure-hue',
    tab: 'chroma',
    name: 'Pure Hue',
    paletteName: 'Lemon/Magenta',
    values: {
      rings: 4,
      density: 4,
      patternA: null,
      patternB: null,
      colorA: '#fff033',
      colorB: '#ee0099',
      hueShift: 2.2,
      cellBlur: 0.4,
      speed: 0.028,
    },
  },
  {
    id: 'chroma.petal-color',
    tab: 'chroma',
    name: 'Petal Color',
    paletteName: 'Rose/Mint',
    values: {
      rings: 6,
      density: 8,
      patternA: null,
      patternB: null,
      colorA: '#ff7799',
      colorB: '#88ddc0',
      hueShift: 1.3,
      cellBlur: 0.4,
      speed: 0.022,
      kaleidoscope: 8,
    },
  },
  {
    id: 'chroma.spectrum-drift',
    tab: 'chroma',
    name: 'Spectrum Drift',
    paletteName: 'Ink/Spectrum',
    values: {
      rings: 5,
      density: 4,
      patternA: null,
      patternB: null,
      colorA: '#0a0a14',
      colorB: '#ff5500',
      hueShift: 2.6,
      cellBlur: 0.4,
      speed: 0.024,
    },
  },
]

// ─── Dev-only validation presets ──────────────────────────────────
// Chunk 1.5 added these to pin a single new uniform at a visibly
// distinctive value while leaving everything else at SUNBURST
// baseline. They keep `tab: 'signature'` so the union namespace is
// stable, but the slugs preserve the `__validate-…` prefix so chunks
// 3+ can filter them out of user-facing tabs (recommended: hide
// behind a debug toggle, surface only via direct id reference).
//
// Filter rule for tab UIs: id.includes('.__validate-')
export const DEV_PRESETS: Preset[] = [
  {
    id: 'signature.__validate-kaleido',
    tab: 'signature',
    name: '__VALIDATE_KALEIDO',
    paletteName: 'Diag Yellow/Velvet',
    values: {
      rings: 6,
      density: 6,
      speed: 0.02,
      kaleidoscope: 8,
      patternA: 'diagonal',
      patternB: 'diagonal',
      colorA: '#ffcc00',
      colorB: '#4a0e60',
    },
  },
  {
    id: 'signature.__validate-chroma',
    tab: 'signature',
    name: '__VALIDATE_CHROMA',
    paletteName: 'White/Black Split',
    values: { rings: 30, density: 4, speed: 0.02, chromatic: 0.6 },
  },
  {
    id: 'signature.__validate-hue',
    tab: 'signature',
    name: '__VALIDATE_HUE',
    paletteName: 'White/Black Drift',
    values: { rings: 30, density: 4, speed: 0.02, hueShift: 1.5 },
  },
]
